-- Tâches GSA : schéma multi-comités et sécurité côté base
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, nom text, prenom text, actif boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.committees (id uuid primary key default gen_random_uuid(), nom text not null, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.memberships (user_id uuid references auth.users(id) on delete cascade, committee_id uuid references public.committees(id) on delete cascade, role text not null default 'member' check (role in ('admin','member','external')), primary key(user_id, committee_id));
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), committee_id uuid not null references committees(id) on delete cascade, section_id text, sous_section text, titre text not null, responsables uuid[] not null default '{}', status_id text, delai date, remarque text default '', event_id text, meeting_id text, checklist jsonb not null default '[]', parent_id uuid references tasks(id), documents jsonb not null default '[]', delai_ref jsonb, recurrence text, postes_resp text[] default '{}', suivante_id uuid, terminee_le date, created_by uuid references auth.users(id), updated_at timestamptz not null default now());
create table if not exists public.meetings (id uuid primary key default gen_random_uuid(), committee_id uuid not null references public.committees(id) on delete cascade, data jsonb not null default '{}');
create table if not exists public.events (id uuid primary key default gen_random_uuid(), committee_id uuid not null references public.committees(id) on delete cascade, data jsonb not null default '{}');
create table if not exists public.people (id uuid primary key default gen_random_uuid(), committee_id uuid not null references public.committees(id) on delete cascade, user_id uuid references auth.users(id), data jsonb not null default '{}');
create table if not exists public.statuses (id text, committee_id uuid references public.committees(id) on delete cascade, data jsonb not null default '{}', primary key(id, committee_id));
create table if not exists public.sections (id text, committee_id uuid references public.committees(id) on delete cascade, data jsonb not null default '{}', primary key(id, committee_id));
create table if not exists public.roles (id text, committee_id uuid references public.committees(id) on delete cascade, data jsonb not null default '{}', primary key(id, committee_id));
create table if not exists public.polls (id uuid primary key default gen_random_uuid(), committee_id uuid references public.committees(id) on delete cascade, data jsonb not null default '{}');
create table if not exists public.app_state (user_id uuid references auth.users(id) on delete cascade, committee_id uuid references public.committees(id) on delete cascade, data jsonb not null, updated_at timestamptz default now(), primary key(user_id, committee_id));

create or replace function public.is_committee_member(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships where committee_id=cid and user_id=auth.uid()); $$;
create or replace function public.is_committee_admin(cid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from memberships where committee_id=cid and user_id=auth.uid() and role='admin'); $$;
alter table profiles enable row level security; alter table committees enable row level security; alter table memberships enable row level security; alter table tasks enable row level security; alter table meetings enable row level security; alter table events enable row level security; alter table people enable row level security; alter table statuses enable row level security; alter table sections enable row level security; alter table roles enable row level security; alter table polls enable row level security; alter table app_state enable row level security;
create policy profiles_self_or_member on profiles for select using (id=auth.uid() or exists(select 1 from memberships m where m.user_id=profiles.id and is_committee_member(m.committee_id)));
create policy committees_member on committees for select using (is_committee_member(id));
create policy committees_admin_insert on committees for insert with check (auth.uid()=created_by);
create policy committees_admin_update on committees for update using (is_committee_admin(id));
create policy committees_admin_delete on committees for delete using (is_committee_admin(id));
create policy memberships_member_read on memberships for select using (is_committee_member(committee_id));
create policy memberships_admin_write on memberships for all using (is_committee_admin(committee_id)) with check (is_committee_admin(committee_id));
create policy tasks_member_or_assignee on tasks for select using (is_committee_member(committee_id) or auth.uid()=any(responsables));
create policy tasks_member_write on tasks for insert with check (is_committee_member(committee_id));
create policy tasks_member_update on tasks for update using (is_committee_admin(committee_id) or auth.uid()=any(responsables) or created_by=auth.uid());
create policy tasks_admin_delete on tasks for delete using (is_committee_admin(committee_id));
-- Les autres entités suivent la même frontière de comité; les externes n'accèdent qu'aux lignes explicitement assignées.
create policy meetings_member on meetings for all using (is_committee_member(committee_id)) with check (is_committee_member(committee_id));
create policy events_member on events for all using (is_committee_member(committee_id)) with check (is_committee_member(committee_id));
create policy people_member on people for all using (is_committee_member(committee_id)) with check (is_committee_member(committee_id));
create policy lists_member on statuses for all using (is_committee_member(committee_id)) with check (is_committee_member(committee_id));
create policy sections_member on sections for all using (is_committee_member(committee_id)) with check (is_committee_member(committee_id));
create policy roles_admin on roles for all using (is_committee_admin(committee_id)) with check (is_committee_admin(committee_id));
create policy polls_member on polls for all using (is_committee_member(committee_id)) with check (is_committee_member(committee_id));
create policy state_owner on app_state for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,nom,prenom) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'nom',''),coalesce(new.raw_user_meta_data->>'prenom','')); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
